export interface MovieData {
    adult: any,
    backdrop_path: any,
    genre_ids: [],
    id: any,
    original_language: any,
    original_title: any,
    overview: any,
    popularity: any,
    poster_path: any,
    release_date: any,
    title: any,
    video: any,
    vote_average: any,
    vote_count: any,
}